// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzihrnecsmkflxitejrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6aWhybmVjc21rZmx4aXRlanJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzI3MDAsImV4cCI6MjA2NDcwODcwMH0.9bS9cz_O_GGs2OLQ7Vz0t9UlPEatIZmy4n5cyH8BJfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);